- .github/workflows/build.yml
`github.head_ref` is only set on pull request events, so we should handle push events differently. There isn't an alternative variable, but we can only push to the main branch so we know that will be the branch name.
> VEGA-839: Always extract the branch name

- .github/workflows/build.yml
To ensure that we push both `latest` and the semver tag
> VEGA-839: Push all tags on main branch builds

- cypress/integration/cases.spec.js
- internal/server/all_cases.go
- internal/server/all_cases_test.go
- internal/server/dashboard.go
- internal/server/dashboard_test.go
- internal/server/server.go
- internal/sirius/cases_by_assignee.go
- internal/sirius/cases_by_assignee_test.go
- web/template/all-cases.gotmpl
- web/template/dashboard.gotmpl
- web/template/tasks.gotmpl
Adds filtering and pagination to the `CasesByAssignee` API call, so it can be shared between this handler and pending-cases.
The new handler also shares the `dashboard` template, but with slightly different columns based on flags.
Adds links from existing tabs/pages.
Fixes VEGA-829
<details><summary>Preview</summary>
</details>
> VEGA-829: View all cases

- internal/server/server.go
- web/template/all-cases.gotmpl
- web/template/dashboard.gotmpl
- web/template/tasks.gotmpl
So that it can be hosted at `/lpa/dashboard`
> Use prefix in links and redirects

- internal/server/landing_page.go
- internal/server/landing_page_test.go
- internal/server/server.go
When a user goes to `/`, they should be redirected to `/pending-cases` if they're a case worker and `/teams/central` if they're a manager.
Fixes VEGA-812
> Determine correct landing page

- .github/workflows/build.yml
Backporting some changes from the user management repo to speed up CI and make dependabot work.
- Build and cache images up-front so they're not rebuilt for acceptance testing steps
- Compare Pacts to latest if building for dependabot, rather than pushing to the broker (because dependabot doesn't have write access)
- Don't push images if building for dependabot (because dependabot doesn't have write access)
> Improve CI processes

- .github/workflows/build.yml
- cypress/integration/user-all-cases.spec.js
- cypress/integration/user-pending-cases.spec.js
- cypress/integration/user-tasks.spec.js
- internal/server/server.go
- internal/server/user_all_cases.go
- internal/server/user_all_cases_test.go
- internal/server/user_pending_cases.go
- internal/server/user_pending_cases_test.go
- internal/server/user_tasks.go
- internal/server/user_tasks_test.go
- internal/sirius/cases_by_assignee.go
- internal/sirius/user_test.go
- web/template/layout/page.gotmpl
- web/template/user-all-cases.gotmpl
- web/template/user-pending-cases.gotmpl
- web/template/user-tasks.gotmpl
**NB: Forked from VEGA-834. Once that's merged, this can be rebased against main**
Adds the full pending cases/all cases/tasks pages for the manager view of a caseworker. Includes table contents, navigation and backlinks to the team.
Adds expectation for `client.User()` to return the user's teams.
Fixes VEGA-835 and VEGA-836
> VEGA-835/VEGA-836: Manager view of caseworker dashboard

- internal/server/pending_cases.go
- internal/server/pending_cases_test.go
- internal/sirius/criteria.go
- internal/sirius/my_details.go
- internal/sirius/my_details_test.go
- web/template/pending-cases.gotmpl
Non-case workers should not be able to request that cases are assigned to them from the central pot.
This is also enforced in the API, but this change is to make the UI clearer.
Fixes VEGA-855
> VEGA-855: Only show Request cases button to case workers

- package.json
- yarn.lock
Major updates to webpack and copy-webpack-plugin get past security vulnerabilities in set-value and glob-parent
> Upgrade dependencies to fix security vulnerabilities

- internal/server/card_payments.go
- internal/server/card_payments_test.go
- web/template/card-payments.gotmpl
Card Payment users should not be limited to a particular number of tasks, so never disabled the button.
Fixes VEGA-1029 #patch
> Always allow Card Payment users to request a task

- internal/sirius/cases_by_assignee.go
- internal/sirius/cases_by_assignee_test.go
If `CasesByAssignee` returns an error, we should return it immediately rather than trying to calculate if there's a workable case.
Since the error occurred, pagination is likely to be `nil` and therefore `pagination.TotalItems` causes a panic
> Fix return of HasWorkableCase

- .github/workflows/build.yml
`github.head_ref` is only set on pull requests, so fallback to `main` on other builds.
> Set PACT_TAG to branch name

- package.json
To ensure we avoid a security issue in >1.4.4.
Can be removed when the package is back under secure control, or our core dependencies stop using it.
> Pin colors to 1.4.0 #patch

- go.mod
- go.sum
- internal/server/server.go
- internal/server/server_test.go
- web/template/layout/header.gotmpl
Allows us to apply standardised security headers across all apps. Specifically, this app is missing the Cache-Control header.
#patch
> Use security headers from opg-go-common

- cypress/e2e/tasks-dashboard.cy.js
- internal/server/redirect.go
- internal/server/redirect_test.go
- internal/server/request_next_task.go
- internal/server/request_next_task_test.go
- internal/server/server.go
- internal/server/tasks_dashboard.go
- internal/server/tasks_dashboard_test.go
- internal/sirius/my_details.go
- internal/sirius/my_details_test.go
- web/template/tasks-dashboard.gotmpl
So that it can be used by members of multiple teams.
The page title is now "{team name} Dashboard" rather than being hard-coded as "Card payments"
Fixes VEGA-1445 #major
> Move the "Card Payments" page to "Tasks Dashboard"

- cypress/e2e/all-cases.cy.js
- cypress/e2e/central-cases.cy.js
- cypress/e2e/feedback.cy.js
- cypress/e2e/navigation.cy.js
- cypress/e2e/pending-cases.cy.js
- cypress/e2e/reassign.cy.js
- cypress/e2e/tasks-dashboard.cy.js
- cypress/e2e/tasks.cy.js
- cypress/e2e/team-work-in-progress.cy.js
- cypress/e2e/user-all-cases.cy.js
- cypress/e2e/user-pending-cases.cy.js
- cypress/e2e/user-tasks.cy.js
- internal/sirius/assign_test.go
- internal/sirius/cases_by_assignee_test.go
- internal/sirius/cases_by_team_test.go
- internal/sirius/cases_with_open_tasks_by_assignee_test.go
- internal/sirius/client_test.go
- internal/sirius/feedback_test.go
- internal/sirius/mark_worked_test.go
- internal/sirius/my_details_test.go
- internal/sirius/request_next_cases_test.go
- internal/sirius/request_next_task_test.go
- internal/sirius/tasks_by_assignee_test.go
- internal/sirius/team_test.go
- internal/sirius/teams_test.go
- internal/sirius/user_by_email_test.go
- internal/sirius/user_test.go
Pact requests are now authenticated sirius side so there is no need to set headers and cookies in pact/cypress tests.
#minor
> VEGA-1446 remove headers and cookies from pact and cypress tests

- .github/workflows/build.yml
- docker/cypress/Dockerfile
- docker/docker-compose.ci.yml
Use the prebuilt GitHub Action rather than maintaining our own image. This also means that everything uses the Cypress version specified in `package.json`.
#patch
> Use cypress-io/github-action

- docker/sirius-lpa-dashboard/Dockerfile
Moves Node to LTS release and a more recent version of Alpine
#patch
> Bump node image to 18.13.0-alpine3.17

- internal/sirius/assign.go
- internal/sirius/cases_by_assignee.go
- internal/sirius/cases_by_team.go
- internal/sirius/cases_with_open_tasks_by_assignee.go
- internal/sirius/feedback.go
- internal/sirius/mark_worked.go
- internal/sirius/my_details.go
- internal/sirius/request_next_cases.go
- internal/sirius/request_next_task.go
- internal/sirius/tasks_by_assignee.go
- internal/sirius/team.go
- internal/sirius/teams.go
- internal/sirius/user.go
- internal/sirius/user_by_email.go
We don't care about errors when closing the body of an API request
Fixes VEGA-1706 #patch
> Ignore gosec false positives

- .github/renovate.json
Turn off lockfile maintenance in Renovate: it only updates transient dependencies, which creates lots of noise and doesn't provide us with any benefit
> Disable lockfile maintenance

- package.json
- web/assets/load-classes.js
- web/assets/main.js
- web/assets/main.scss
- web/template/layout/page.gotmpl
- yarn.lock
- Update path references to include `/dist`
- Move body-class-setting into separate file (it needs to be done before we import govuk-frontend and we block inline scripts)
- Update icon paths
For VEGA-2202 #minor
> Upgrade govuk-frontend and moj-frontend

- internal/server/server.go
- internal/server/server_test.go
If the request is cancelled, issue a 499 response and return immediately. Don't render a template, as it will never be shown. Don't log the error, as we know what it is and have handled it.
#minor
> Handle cancelled requests

- internal/server/server.go
- internal/server/server_test.go
If the API responds with a HTTP status error, copy the status code from that error onto the response.
This makes the status code and response the user sees more accurate. For example, if Sirius returns a 403 response the user will now see a "Forbidden" page rather than "An error has occurred".
This also stops error-level logging of 4XX responses.
Fixes CTC-175 #patch
> Improve handling of Sirius API errors
